#!/bin/sh
t0-1 serve-rag \
--k 5 \
--db-choice chroma \
--llm-provider openai_completion \
--llm-model-name TomasLaz/t0-2.5-gemma-3-27b-it \
--budget-forcing \
--budget-forcing-kwargs '{"max_tokens_thinking": 512, "num_stop_skips": 0}' \
--extra-body '{"max_tokens": 4096, "seed": 42, "temperature": 0}' \
--conversational \
--conversational-agent-llm-provider openai \
--conversational-agent-llm-model-name openai/gpt-oss-20b \
--conversational-agent-extra-body '{"max_tokens": 4096, "seed": 42, "temperature": 0}' \
--prompt-template-path ./templates/rag_prompt_conversational.txt \
--system-prompt-path ./templates/rag_system_prompt_conversational.txt \
--conditions-file ./data/nhs-conditions/v4/qwen_summarised_conditions.jsonl \
--persist-directory ./v4-summarised-db \
--local-file-store ./v4-summarised-lfs \
--host 0.0.0.0 \
--port 8050 \
--seed 42
